language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - php: '7.1'
    - php: '7.2'
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi;

script:
  - vendor/bin/phpunit -d memory_limit=512M -v tests
  - vendor/bin/php-cs-fixer fix src --allow-risky=yes --dry-run
  - vendor/bin/php-cs-fixer fix src --allow-risky=yes --dry-run
